spring.datasource.url=jdbc:postgresql://localhost:52345/vollmed_api
spring.datasource.username=postgres
spring.datasource.password=devDB
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true